### ISSUE TITLE
v0.0.16 checklist

### ISSUE THREAD

**Issue by undisbeliever** [undisbeliever/terrific-audio-driver#38]
* [x] Fix failing `test_subroutine_instrument_hint_and_loop` test
 * [x] Add a better instrument after loop tests
 * [x] Review bytecode state after loop tests
 * [x] Fix bytecode state after loop

 * [x] Add `{P$1000 c}` portamento
 * [x] Add `portamento_pitch` instruction
 * [x] Add `{c P$1000}` and `{P$1000 P$1800)` portamento
 * [x] Add `PR` MML command
 * [x] Add `c& {d}` portamento support
 * [x] Add `P` and `PR` to broken chord

 * [x] Add `PF` MML command (include portamento and broken chord)

 * [x] Use subroutine instrument hint in tad-gui subroutine preview
