### ISSUE TITLE
v0.1.0 checklist

### ISSUE THREAD

**Issue by undisbeliever** [undisbeliever/terrific-audio-driver#39]
* [x] Improve MML unit tests
    * [x] Split into separate files (`mml.rs` is too large to manage)
    * [x] Review unit tests
    * [x] Add missing error tests

---

 * [x] Review MML
 * [x] Compare my MML syntax against PMDMML syntax
 * [x] Add `(` and `)` volume MML commands (to match PMDMML and ctrmml)
 * [x] Add `l` to tick arguments to match PMDMML (ie, `ql8` and `vs+5,l4`)

---

 * [x] Add `skip_last_loop_u16be` bytecode instruction
    * Will require extending song data after the 8 bit `skip_last_loop` to `skip_last_loop_u16`.
    * [x] Find a way to test large nested loops `[ c : [ c : [ c : [ <very long> ]2 ]2 ]2`
      * Maybe use bc_interpreter and check tick count and note/instrument state is correct
    * [x] Also test 8 and 16 bit skip-last-loop instructions in the same song
    * [x] Confirm it will not cause issues with `L` song loop.  It shouldn't as `L` is forbidden inside a loop.

---

 * [x] Add echo register shadow variables
    * [x] Move set echo registers into `__process_channels()`
    * [x] Immediately process the first music channel on song start to set the echo registers
 * [x] Add maximum echo delay to song
 * [x] Add echo instructions
 * [x] Merge echo feedback and FIR tap instructions to free up opcodes.

---

 * [x] Add state viewer window
   * Instruments, Envelopes, Volume, Pan, Echo, etc
 * ~~Show if the audio driver has lagged in the state viewer~~

---

 * [x] Remove `blank-song.bin`
   * [x] Add a bit-array for enabled channels to the song header (This will shrink song-data size if 1 or more channel is unused)
   * [x] Clear echo variables if song uses no channels
   * [x] Replace `Tad_BlankSong_Bin` and `Tad_BlankSong_SIZE` import with a hard-coded 0 byte.

 * [x] Add surround mode
 * [x] Add music and sound effects volume
    * Intended to quiet sound in a pause menu while still allowing sound effects at full volume

---

  * [x] Rearrange firstpage/lastpage variables to use `direct_page=true` in `__reset_channel()`
    * [x] Confirm lastpage holds as many uninitialised variables as possible.
    * [x] Double check all `direct_page = true` usage only modifies lastpage variables.

---

 * [x] Add sound effect subroutines
   * `call_subroutine` can check if the channel is a SFX channel
   * SFX subroutines are written as MML the sound_effects.txt header
      * Bytecode SFX subroutine can be written using the `\asm { }` command
      * This will be a breaking change as the header was plain text (no `;` comments required).

 * [x] Confirm `\n===` is forbidden in sound effects.
 * [x] Document `\n===` is forbidden in sound effects.
 * [x] Silently convert `\n===` to `;\n===` when saving sound effects

---

 * [x] Review instruction list to make sure I haven't forgotten anything

 * [x] Split example project into example and tests
    * Some of the examples are not intended for humans to review
    * Some of the examples are for manually testing with an audio editor
 * [x] Confirm all examples in the example project sound correct

---

 * [x] Fuzz the bytecode assembler
 * [x] Fuzz the MML parser

 * ~~Draw an icon and/or logo~~

 * [x] Review mml-syntax and bytecode-syntax
 * [x] Review changelog
 * [x] Update README feature list

 * [x] Document the MML and bytecode syntax has been stabilised

**Comment by undisbeliever** [comment]
Ready to release v0.1.0 and declare the MML and bytecode assembly syntax and behaviour stable.
